services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: visorsig-api
    restart: unless-stopped
    ports:
      - "5080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__VisorDatosSIG=Server=tcp:visordatossig.database.windows.net,1433;Initial Catalog=VisorDatosSIG;Persist Security Info=False;User ID=AdminSIG;Password=Admin123!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
      - Jwt__Key=E6ip+mGK9+OytajSplNpUnYJxGyQ0mGKpSLm2BK5AHk=
      - Jwt__Issuer=VisorDatosSIG.Api
      - Jwt__Audience=VisorDatosSIG.Clientes
      - Jwt__ExpirationMinutes=480
      - Cors__AllowedOrigins__0=http://localhost:5000
      - Cors__AllowedOrigins__1=http://localhost:5080
      - Cors__AllowedOrigins__2=http://localhost:3000
      - Cors__AllowedOrigins__3=http://localhost:5173

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: visorsig-web
    restart: unless-stopped
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - Api__BaseUrl=http://localhost:5080
    depends_on:
      - api
